---
version: 2
project_name: atmos-proxy
archives:
- name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
builds:
- binary: atmos-proxy
  main: cmd/atmos-proxy/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
release:
  prerelease: true
  header: |
    [Pull Requests](https://github.com/aquaproj/atmos-proxy/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/aquaproj/atmos-proxy/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/aquaproj/atmos-proxy/compare/{{.PreviousTag}}...{{.Tag}}
signs:
- cmd: cosign
  artifacts: checksum
  signature: ${artifact}.sig
  certificate: ${artifact}.pem
  output: true
  args:
  - sign-blob
  - "-y"
  - --output-signature
  - ${signature}
  - --output-certificate
  - ${certificate}
  - --oidc-provider
  - github
  - ${artifact}
